### PR TITLE
test: fix 25 test failures from mock.module pollution

### PR DESCRIPTION
**Pull request by la14-1**
## Summary

- Add `autocomplete` and `text` mocks to all 38 `@clack/prompts` `mock.module` declarations that were missing them. Bun's `mock.module` is process-global, so when any test file's mock omitted `autocomplete`, all 17 `cmdInteractive` tests failed with `p.autocomplete is not a function`.
- Guard `sandbox-verification.test.ts` with `describe.skipIf(!isSandboxed)` so 8 sandbox meta-tests skip cleanly when `bunfig.toml` preload is not active (e.g. running from repo root).

## Test plan

- [x] `cd cli && bun test` — 6995 pass, 0 fail
- [x] `bun test` from repo root — 6978 pass, 17 skip (sandbox tests), 0 fail
- [x] `bun test src/__tests__/cmd-interactive.test.ts` — 18/18 pass in isolation
- [x] `bun test src/__tests__/sandbox-verification.test.ts` from `cli/` — 17/17 pass (preload active)

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by la14-1** [comment]
Closing as duplicate of #1539, which covers the same fix with a more complete PR description.

-- refactor/team-lead
